/*
 * HTMLInterpreter.h
 *
 *  Created on: Apr 5, 2016
 *      Author: wojciech
 */

#ifndef INTERPRETER_HTMLINTERPRETER_H_
#define INTERPRETER_HTMLINTERPRETER_H_

#include<vector>
#include "ResultModel.h"
#include "../parser/HTMLElement.h"

/**
 * Interprets data generated by HTMLParser.
 */
class HTMLInterpreter
{
public:
	/**
	 * Default Constructor for HTMLInterpreter.
	 * @param root root HTMLElement for document to be interpreted
	 */
	HTMLInterpreter(HTMLElement* root);
	virtual ~HTMLInterpreter();

	/**
	 * Interprets HTMLElement specified in constructor and generates models
	 * of entries of the table in parsed html document.
	 */
	std::vector<ResultModel*> interpret();

private:
	//Root of the whole document
	HTMLElement* root;

	static const std::map<std::string, ThreatType> stringToThreatType;
	static const std::map<std::string, MalwareType> stringToMalwareType;

	/**
	 * Method that looks for a table with a class of "maintable"
	 * @param startFrom HTMLElement that should be searched
	 * @returns main table from HTML document, or nullptr if not found
	 */
	HTMLElement* getTableRoot(HTMLElement* startFrom);

	/**
	 * Method that interprets single row from HTML table.
	 * @param tableRow HTMLElement from which to generated data
	 * @returns generatet ResultModel data from tableRow
	 */
	ResultModel* interpretTableRow(HTMLElement* tableRow);


};

#endif /* INTERPRETER_HTMLINTERPRETER_H_ */
